# This Docker Compose configuration is set up for a development environment.
# *Do not* use this in production.
#
# Start the Docker container with:
#   docker compose -f compose-dev.yaml up -d

version: '3'

networks:
  umcu_net:

volumes:
  db_data: { }
  grafana_data: { }
  proxy_data: { }
  proxy_letsencrypt: { }

services:
  db:
    image: mariadb:11.2.2
    # Set database username, password, and name.
    #   These values must match the corresponding variables in the "app" and "proxy" services.
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=1
      - MARIADB_USER=umcu               # It is recommended to change this.
      - MARIADB_PASSWORD=ChangeMe       # Create your own secure password.
      - MARIADB_DATABASE=umcu           # It is recommended to change this.
    expose:
      - 3306 # Do not change this unless you know what you're doing!
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - umcu_net
    restart: unless-stopped

  # This service will not be publicly accessible, please use Grafana for that.
  # Please change the username and password in 'prometheus.yml'.
  #   See: https://prometheus.io/docs/guides/basic-auth/
  #   Default password is "ChangeMe"
  prometheus:
    image: prom/prometheus
    expose:
      - 9090 # Do not change this unless you know what you're doing!
    networks:
      - umcu_net
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped

  # This service is publicly accessible (via username and password).
  #   The default username and password are both "admin".
  #   You will be prompted to change the password. Make this secure!
  grafana:
    image: grafana/grafana
    expose:
      - 3000 # Do not change this unless you know what you're doing!
    volumes:
      - ./grafana_data:/var/lib/grafana
    networks:
      - umcu_net
    depends_on:
      - prometheus
    restart: unless-stopped

  app:
    build: .
    environment:
      - KTOR_ENV=prod     # Setting this to "dev" will tell the app to use the H2 embedded database.
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=umcu      # Must match the "MARIADB_USER" variable in the "db" service.
      - DB_PASS=ChangeMe  # Must match the "MARIADB_PASSWORD" variable in the "db" service.
      - DB_NAME=umcu      # Must match the "MARIADB_DATABASE" variable in the "db" service.
      - RATE_LIMIT=100    # How many requests are allowed per minute.
    expose:
      - 8080 # Do not change this unless you know what you're doing!
    networks:
      - umcu_net
    depends_on:
      - db
      - grafana
    restart: unless-stopped

  proxy:
    image: jc21/nginx-proxy-manager:latest
    ports:
      - "80:80"   # HTTP. Do not change this.
      - "81:81"   # Admin panel. Change the left side to change which port is used on your host machine.
    environment:
      - DB_MYSQL_HOST=db
      - DB_MYSQL_PORT=3306
      - DB_MYSQL_USER=umcu          # Must match the "MARIADB_USER" variable in the "db" service.
      - DB_MYSQL_PASSWORD=ChangeMe  # Must match the "MARIADB_PASSWORD" variable in the "db" service.
      - DB_MYSQL_NAME=umcu          # Must match the "MARIADB_DATABASE" variable in the "db" service.
    volumes:
      - ./proxy_data:/data
      - ./proxy_letsencrypt:/etc/letsencrypt
    networks:
      - umcu_net
    depends_on:
      - db
      - app
    restart: unless-stopped
