ktor:
  development: "$KTOR_DEVELOPMENT:true"
  application:
    modules:
      - app.umcu.api.ApplicationKt.module
    rate_limit: "$RATE_LIMIT:100" # how many requests to the api per minute
  deployment:
    port: 8080
postgres:
  db: "$POSTGRES_DB:"
  user: "$POSTGRES_USER:"
  password: "$POSTGRES_PASSWORD:"
tmdb_api_key: "$TMDB_API_KEY:"
