# Ktor application
ktor:
  development: "$KTOR_DEVELOPMENT:true"
  application:
    modules:
      - app.umcu.api.ApplicationKt.module
    rate_limit: "$RATE_LIMIT:100" # How many requests can be made to the API per minute
  deployment:
    host: 0.0.0.0
    port: 8080
# Postgres database
postgres:
  db: "$POSTGRES_DB:" # Database name
  user: "$POSTGRES_USER:" # Username
  password: "$POSTGRES_PASSWORD:" # Password
# TMDB API
tmdb_read_access_token: "$TMDB_READ_ACCESS_TOKEN:" # API Read Access Token (see: https://www.themoviedb.org/settings/api)
